#!/usr/bin/env python3
"""Bench tool for the provisioning record — RADIO_PROTOCOL.md §10.1, dongle/BUILD_SPEC.md §9.

Generates the three provisioning records for one set (dongle, RED, GREEN)
from a serial: random LE static-random addresses and a random shared set key.
Writes each as a small generated C header, `provisioning_data.h`, in its own
per-role output directory — PLAN.md §4's binding decision, 2026-08-12: identity
is baked into the firmware image at build time rather than read from a flash
partition written by a separate step. Point `west build` at the directory with
`-DCONFIG_PROVISIONING_HEADER_DIR=<dir>`; CMakeLists.txt refuses to configure without
one, so there is no such thing as a build with no real identity.

    python provision.py RR-0001
    python provision.py RR-0001 -o out/

Then, for each role, the build command this tool prints, e.g.:

    west build -b raytac_mdbt50q_cx_40_dongle/nrf52840 dongle -d dongle/build-radio \\
        -- -DCONFIG_DONGLE_RADIO=y '-DCONFIG_PROVISIONING_HEADER_DIR="<abs path>/out/RR-0001_dongle"'

Deliberately dependency-free beyond the Python standard library.

The manifest this writes, and the generated headers themselves, contain the
set's shared key in the clear. Treat them as manufacturing-floor material, not
something to commit or mail — RADIO_PROTOCOL.md §10.4 already notes set_key is
stored in plain flash and depends on APPROTECT, not this tool, for protection
against physical access.
"""
import argparse
import re
import secrets
import sys
from pathlib import Path

# ---------------------------------------------------------------------------
# Record layout — must track common/provisioning.h exactly. See that header
# for why the role enum's numeric values are pinned rather than assumed.
# ---------------------------------------------------------------------------

SERIAL_LEN = 12
ADDR_LEN = 6
KEY_LEN = 16

ROLE_DONGLE, ROLE_RED, ROLE_GREEN = 0, 1, 2
ROLE_NAMES = {ROLE_DONGLE: "dongle", ROLE_RED: "red", ROLE_GREEN: "green"}
ROLE_ENUM = {
    ROLE_DONGLE: "PROVISIONING_ROLE_DONGLE",
    ROLE_RED: "PROVISIONING_ROLE_RED",
    ROLE_GREEN: "PROVISIONING_ROLE_GREEN",
}

SERIAL_RE = re.compile(r"^[A-Z0-9-]{1,%d}$" % SERIAL_LEN)


def zero_addr():
    return bytes(ADDR_LEN)


def random_static_addr():
    """An LE static random identity address — RADIO_PROTOCOL.md §10.2: the two
    most significant bits of the most significant octet must be 1. Zephyr's
    bt_addr_t.val[] is ordered so val[5] is that octet."""
    addr = bytearray(secrets.token_bytes(ADDR_LEN))
    addr[5] |= 0xC0
    return bytes(addr)


# ---------------------------------------------------------------------------
# Generated header — a struct literal, not a byte layout. No packing, no CRC:
# see common/provisioning.h's header comment for why that machinery is gone.
# ---------------------------------------------------------------------------

def _c_bytes(data):
    return "{" + ", ".join("0x%02X" % b for b in data) + "}"


def write_header(path, set_serial, role, own_addr, peer_addrs, set_key):
    serial_literal = set_serial.encode("ascii").decode("ascii")
    lines = [
        "/* Generated by dongle/tools/provision.py — DO NOT EDIT, DO NOT COMMIT.",
        " * Set %s, role %s." % (set_serial, ROLE_NAMES[role]),
        " *",
        " * Contains this unit's identity and the shared set key in the clear.",
        " * Manufacturing-floor material — RADIO_PROTOCOL.md §10.4. See",
        " * common/provisioning.h for the struct this populates. */",
        "#ifndef PROVISIONING_DATA_H_",
        "#define PROVISIONING_DATA_H_",
        "",
        '#include "provisioning.h"',
        "",
        "static const struct provisioning_record PROV_RECORD = {",
        '\t.set_serial = "%s",' % serial_literal,
        "\t.role = %s," % ROLE_ENUM[role],
        "\t.own_addr = %s," % _c_bytes(own_addr),
        "\t.peer_addr = {",
        "\t\t%s," % _c_bytes(peer_addrs[0]),
        "\t\t%s," % _c_bytes(peer_addrs[1]),
        "\t},",
        "\t.set_key = %s," % _c_bytes(set_key),
        "};",
        "",
        "#endif /* PROVISIONING_DATA_H_ */",
        "",
    ]
    path.write_text("\n".join(lines), encoding="utf-8")


# ---------------------------------------------------------------------------

def build_set(set_serial):
    dongle_addr = random_static_addr()
    red_addr = random_static_addr()
    green_addr = random_static_addr()
    set_key = secrets.token_bytes(KEY_LEN)

    peer_addrs = {
        ROLE_DONGLE: (red_addr, green_addr),
        ROLE_RED: (dongle_addr, zero_addr()),
        ROLE_GREEN: (dongle_addr, zero_addr()),
    }
    own_addrs = {ROLE_DONGLE: dongle_addr, ROLE_RED: red_addr, ROLE_GREEN: green_addr}
    return own_addrs, peer_addrs, set_key


def addr_str(a):
    return ":".join("%02X" % b for b in a)


def write_manifest(path, set_serial, own_addrs, set_key, header_dirs):
    lines = [
        "RefRemote provisioning manifest",
        "set_serial: %s" % set_serial,
        "set_key:    %s" % set_key.hex().upper(),
        "",
        "SENSITIVE - the key above is this set's shared secret in the clear.",
        "Bench/manufacturing record only. Do not commit, mail, or archive",
        "alongside anything public. RADIO_PROTOCOL.md section 10.4.",
        "",
    ]
    for role in (ROLE_DONGLE, ROLE_RED, ROLE_GREEN):
        lines.append("[%s]" % ROLE_NAMES[role])
        lines.append("  own_addr: %s" % addr_str(own_addrs[role]))
        lines.append("  header:   %s" % (header_dirs[role] / "provisioning_data.h"))
        lines.append("")
    path.write_text("\n".join(lines), encoding="utf-8")


def build_command(role, header_dir):
    # CONFIG_PROVISIONING_HEADER_DIR is a Kconfig string, so its value must
    # carry literal double quotes to survive into the generated config
    # fragment (dongle/BUILD_SPEC.md §9) — and forward slashes, not backslashes,
    # sidestep a Windows command-line quirk where a backslash immediately
    # before a closing double quote can be read as an escape. Wrapping the
    # whole -D token in single quotes is what makes the printed line paste
    # straight into PowerShell *and* bash unmodified: both shells pass a
    # single-quoted argument through literally, quotes and all.
    header_str = str(header_dir.resolve()).replace("\\", "/")
    prov_arg = "'-DCONFIG_PROVISIONING_HEADER_DIR=\"%s\"'" % header_str

    if role == ROLE_DONGLE:
        return (
            "west build -b raytac_mdbt50q_cx_40_dongle/nrf52840 dongle -d dongle/build-radio -- "
            "-DCONFIG_DONGLE_RADIO=y %s" % prov_arg
        )
    return (
        "west build -b nrf52840dk/nrf52840 remote -d remote/build -- "
        "%s" % prov_arg
    )


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                  formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("serial", help="set serial, [A-Z0-9-], up to %d chars — printed on all three cases" % SERIAL_LEN)
    ap.add_argument("-o", "--outdir", default=".", help="output directory (default: .)")
    args = ap.parse_args()

    if not SERIAL_RE.match(args.serial):
        print("error: serial must match [A-Z0-9-]{1,%d}, got %r" % (SERIAL_LEN, args.serial),
              file=sys.stderr)
        return 1

    outdir = Path(args.outdir)
    outdir.mkdir(parents=True, exist_ok=True)

    own_addrs, peer_addrs, set_key = build_set(args.serial)

    header_dirs = {}
    for role in (ROLE_DONGLE, ROLE_RED, ROLE_GREEN):
        role_dir = outdir / ("%s_%s" % (args.serial, ROLE_NAMES[role]))
        role_dir.mkdir(parents=True, exist_ok=True)
        header_path = role_dir / "provisioning_data.h"
        write_header(header_path, args.serial, role, own_addrs[role], peer_addrs[role], set_key)
        header_dirs[role] = role_dir
        print("wrote %s" % header_path)

    manifest = outdir / ("%s_manifest.txt" % args.serial)
    write_manifest(manifest, args.serial, own_addrs, set_key, header_dirs)
    print("wrote %s" % manifest)

    print()
    print("Build commands:")
    for role in (ROLE_DONGLE, ROLE_RED, ROLE_GREEN):
        print("  %s" % build_command(role, header_dirs[role]))

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
