/*
 * PCA10059 dummy second-remote firmware — PLAN.md §4.9, queue step S8. Real
 * remote firmware (link.c is remote/src/link.c, unmodified, compiled here by
 * source reference), on a board with one button and two LEDs instead of the
 * DK's seven and four: it holds a connection, consumes the downlink, and
 * generates realistic uplink load (buttons.c), so the dongle's two-connection
 * central scheduling has a real second peer to schedule against — not
 * because this board is meant to model a wrist remote, which PLAN.md §4.9
 * explicitly rejects doing.
 */
#include "provisioning_data.h" /* generated by dongle/tools/provision.py; see CMakeLists.txt */
#include "link.h"
#include "buttons.h"
#include "haptic.h"
#include "indicators.h"

#include <zephyr/kernel.h>
#include <zephyr/drivers/gpio.h>

#define REMOTE_STACK_SIZE 2048
#define REMOTE_PRIORITY   K_PRIO_COOP(7)

static struct k_work_q remote_q;
static K_THREAD_STACK_DEFINE(remote_stack, REMOTE_STACK_SIZE);

/*
 * A19: an unprovisioned unit does not advertise, does not initiate, and
 * renders an unmistakable fault — same requirement as remote/src/main.c's
 * fault_forever(), same reasoning (no console, no CDC-ACM instance to spare
 * here either). This board has one LED simple enough to blink unconditionally
 * without touching the RGB/PWM machinery indicators.c and haptic_init() may
 * not have gotten to initialise yet.
 */
static void fault_forever(void)
{
	static const struct gpio_dt_spec led = GPIO_DT_SPEC_GET(DT_ALIAS(led0), gpios);

	if (gpio_is_ready_dt(&led)) {
		(void)gpio_pin_configure_dt(&led, GPIO_OUTPUT_INACTIVE);
	}

	while (1) {
		(void)gpio_pin_set_dt(&led, 1);
		k_sleep(K_MSEC(200));
		(void)gpio_pin_set_dt(&led, 0);
		k_sleep(K_MSEC(200));
	}
}

int main(void)
{
	/* Boot-time sentinel, belt and braces alongside CMakeLists.txt's
	 * build-time refusal to configure without a provisioning_data.h at
	 * all — same reasoning as remote/src/main.c and dongle/src/engine.c. */
	enum provisioning_status st = provisioning_validate(&PROV_RECORD);

	if (st != PROVISIONING_OK ||
	    (PROV_RECORD.role != PROVISIONING_ROLE_RED &&
	     PROV_RECORD.role != PROVISIONING_ROLE_GREEN)) {
		fault_forever();
		return 0; /* unreached */
	}

	k_work_queue_init(&remote_q);
	k_work_queue_start(&remote_q, remote_stack, K_THREAD_STACK_SIZEOF(remote_stack),
			   REMOTE_PRIORITY, NULL);

	if (haptic_init(&remote_q) != 0) {
		fault_forever();
		return 0;
	}
	if (indicators_init(&remote_q) != 0) {
		fault_forever();
		return 0;
	}
	if (link_init(&PROV_RECORD, &remote_q) != 0) {
		fault_forever();
		return 0;
	}
	if (buttons_init(link_on_gesture, &remote_q) != 0) {
		fault_forever();
		return 0;
	}

	return 0;
}
