<#
.SYNOPSIS
    Generates a provisioning set and builds all three firmwares against it —
    the dongle (radio=y) and both remotes (RED, GREEN) — in one pass.

.DESCRIPTION
    Per-unit build step of the manufacturing workflow (PLAN.md §4.13):
    provisioning identity is baked into each firmware image at build time,
    generated by dongle/tools/provision.py. This script is the generate,
    build-times-three, and package-the-dongle-DFU-zip steps collapsed into
    one command, so programming a labelled set is "run this with the
    serial", not a remembered sequence of steps.

    Deliberately stops short of the actual flashing: the dongle needs its
    bootloader entered by hand (hold the button while plugging in) and a COM
    port chosen, and both are exactly the kind of physical, per-device step
    that should not be silently automated. Packaging the DFU zip has neither
    concern — given a hex file and an output name it's a pure, deterministic
    transform, so it's built here rather than left as a copy-pasted step.
    This script prints the one remaining flash command per device, with real
    paths, rather than running any of them.

.PARAMETER Serial
    The set serial, e.g. RR-0004 — matches provision.py's own format,
    [A-Z0-9-]{1,12}. Not validated twice here; provision.py's own check and
    non-zero exit on failure is the one place that owns this rule.

.EXAMPLE
    .\tools\build_set.ps1 RR-0004

    Can be run directly — it does not need to be dot-sourced. It dot-sources
    tools\ncsenv.ps1 into its own scope internally, which is enough for
    `west` to resolve for the rest of this script's run; nothing needs to
    persist in the calling shell afterward, since the script does everything
    itself before exiting.
#>
param(
    [Parameter(Mandatory = $true, Position = 0)]
    [string]$Serial
)

$RepoRoot = Split-Path -Parent $PSScriptRoot
Set-Location $RepoRoot

function Assert-LastExit($Step) {
    if ($LASTEXITCODE -ne 0) {
        Write-Error "build_set: $Step failed (exit $LASTEXITCODE)"
        exit $LASTEXITCODE
    }
}

# --- 1. Environment -----------------------------------------------------
# Safe to call even if the caller already sourced this in the same window:
# re-running it just re-sets the same PATH/env values, and env vars already
# inherited from the parent shell make `west` resolve regardless. The
# Get-Command check below only exists to skip the noise, not for correctness.
if (Get-Command west -ErrorAction SilentlyContinue) {
    Write-Host "build_set: west already on PATH, skipping ncsenv"
} else {
    . "$RepoRoot\tools\ncsenv.ps1"
}

# --- 2. Provisioning ------------------------------------------------------
$OutDir = "$RepoRoot\dongle\tools\out"
Write-Host "`nbuild_set: generating provisioning for $Serial"
python "$RepoRoot\dongle\tools\provision.py" $Serial -o $OutDir
Assert-LastExit "provision.py"

# provision.py's own CMake-arg forward-slash convention (dongle/tools/
# provision.py's build_command()) — same reason: sidesteps the Windows
# backslash-before-closing-quote quirk when this gets embedded in a quoted
# -D argument below.
$DongleHdr = ("$OutDir\${Serial}_dongle" | Resolve-Path).Path -replace '\\', '/'
$RedHdr    = ("$OutDir\${Serial}_red"    | Resolve-Path).Path -replace '\\', '/'
$GreenHdr  = ("$OutDir\${Serial}_green"  | Resolve-Path).Path -replace '\\', '/'

# --- 3. Build ---------------------------------------------------------------
# Separate build directories per remote role, not the one remote/build this
# project's manual sessions have used so far: this script builds RED and
# GREEN in the same run, and a shared directory would let the second build
# silently overwrite the first's output before either gets flashed.
Write-Host "`nbuild_set: building dongle (radio=y)"
west build -b raytac_mdbt50q_cx_40_dongle/nrf52840 dongle -d dongle/build-radio -- `
    -DCONFIG_DONGLE_RADIO=y "-DCONFIG_PROVISIONING_HEADER_DIR=`"$DongleHdr`""
Assert-LastExit "dongle build"

# --- 3a. Package the dongle DFU zip -----------------------------------------
# Explicit path to the known-good nrfutil, not bare `nrfutil` resolved from
# PATH: this machine has a second copy under the NCS toolchain itself
# (C:\ncs\toolchains\...\nrfutil\bin\nrfutil.exe) without the nrf5sdk-tools
# plugin installed, and which one PATH resolves first is exactly the kind of
# ordering-dependent thing that already caused two separate failures this
# session (the "not recognized" PATH issue, then the NRFUTIL_HOME mismatch —
# tools/ncsenv.ps1 has the full account). Targeting the personal install
# directly sidesteps both classes of failure rather than hoping PATH order
# happens to be right.
Write-Host "`nbuild_set: packaging dongle DFU zip"
$NrfutilExe = "$env:USERPROFILE\.nrfutil\bin\nrfutil.exe"
if (-not (Test-Path $NrfutilExe)) {
    Write-Host "build_set: $NrfutilExe not found, falling back to 'nrfutil' on PATH"
    $NrfutilExe = "nrfutil"
}
$DongleHex = "$RepoRoot\dongle\build-radio\dongle\zephyr\zephyr.hex"
$DongleZip = "$OutDir\${Serial}_dongle\dongle.zip"
& $NrfutilExe nrf5sdk-tools pkg generate --hw-version 52 --sd-req=0x00 `
    --application $DongleHex --application-version 1 $DongleZip
Assert-LastExit "nrfutil pkg generate"

Write-Host "`nbuild_set: building remote RED"
west build -b nrf52840dk/nrf52840 remote -d remote/build-red -- `
    "-DCONFIG_PROVISIONING_HEADER_DIR=`"$RedHdr`""
Assert-LastExit "remote RED build"

Write-Host "`nbuild_set: building remote GREEN"
west build -b nrf52840dk/nrf52840 remote -d remote/build-green -- `
    "-DCONFIG_PROVISIONING_HEADER_DIR=`"$GreenHdr`""
Assert-LastExit "remote GREEN build"

# --- 4. What's next ----------------------------------------------------
Write-Host "`nbuild_set: $Serial built. Flash:"
Write-Host ""
Write-Host "  Dongle (hold its button while plugging in, then):"
Write-Host "    nrfutil nrf5sdk-tools dfu usb-serial -pkg `"$DongleZip`" -p COM<n>"
Write-Host ""
Write-Host "  RED remote:"
Write-Host "    west flash -d remote\build-red"
Write-Host ""
Write-Host "  GREEN remote:"
Write-Host "    west flash -d remote\build-green"
