/*
 * Host unit tests for common/provisioning.c's provisioning_validate() —
 * RADIO_PROTOCOL.md §10.1. Since PLAN.md §4's binding decision (2026-08-12),
 * the record is a compile-time constant generated by dongle/tools/
 * provision.py, not bytes parsed off flash, so there is no CRC/magic/version
 * machinery left to test — only the structural sanity check every build's
 * PROV_RECORD is still run through at boot (dongle/src/engine.c,
 * remote/src/main.c): serial charset, role range, and the all-zero-key
 * sentinel that catches a generated header nobody actually ran the
 * generator for.
 *
 * Deliberately framework-free: `make check`.
 */
#include "../../../common/provisioning.h"

#include <stdio.h>
#include <string.h>

static int checks;
static int failures;

#define CHECK(cond, ...)                                                      \
	do {                                                                   \
		checks++;                                                      \
		if (!(cond)) {                                                 \
			failures++;                                            \
			printf("  FAIL %s:%d: ", __func__, __LINE__);          \
			printf(__VA_ARGS__);                                   \
			printf("\n");                                          \
		}                                                              \
	} while (0)

/* ------------------------------------------------------------------------ */
/* Fixture                                                                   */
/* ------------------------------------------------------------------------ */

static void build(struct provisioning_record *r, enum provisioning_role role)
{
	memset(r, 0, sizeof(*r));
	memcpy(r->set_serial, "RR-0001", 7); /* NUL-padded by the memset above */
	r->role = role;
	for (uint8_t i = 0; i < PROVISIONING_ADDR_LEN; i++) {
		r->own_addr[i] = (uint8_t)(0xC0u | i); /* static-random top bits set */
	}
	for (uint8_t p = 0; p < PROVISIONING_PEER_COUNT; p++) {
		for (uint8_t i = 0; i < PROVISIONING_ADDR_LEN; i++) {
			r->peer_addr[p][i] = (uint8_t)(0xD0u + p * 16 + i);
		}
	}
	for (uint8_t i = 0; i < PROVISIONING_KEY_LEN; i++) {
		r->set_key[i] = (uint8_t)(0xA0u + i);
	}
}

/* ------------------------------------------------------------------------ */
/* Tests                                                                     */
/* ------------------------------------------------------------------------ */

static void valid_record_passes(void)
{
	struct provisioning_record r;

	build(&r, PROVISIONING_ROLE_DONGLE);

	enum provisioning_status st = provisioning_validate(&r);

	CHECK(st == PROVISIONING_OK, "status %s", provisioning_status_str(st));
}

static void all_three_roles_accepted(void)
{
	enum provisioning_role roles[] = {
		PROVISIONING_ROLE_DONGLE, PROVISIONING_ROLE_RED, PROVISIONING_ROLE_GREEN,
	};

	for (size_t i = 0; i < sizeof(roles) / sizeof(roles[0]); i++) {
		struct provisioning_record r;

		build(&r, roles[i]);

		enum provisioning_status st = provisioning_validate(&r);

		CHECK(st == PROVISIONING_OK, "role %d: status %s", roles[i],
		      provisioning_status_str(st));
	}
}

static void serial_bad_char_rejected(void)
{
	struct provisioning_record r;

	build(&r, PROVISIONING_ROLE_DONGLE);
	r.set_serial[0] = 'r'; /* lowercase: outside [A-Z0-9-] */

	enum provisioning_status st = provisioning_validate(&r);

	CHECK(st == PROVISIONING_ERR_SERIAL, "got %s", provisioning_status_str(st));
}

/* A serial using the full 12 bytes with no NUL at all is legitimate — the
 * struct's array is one byte longer than the wire field used to be
 * specifically so a caller always gets a NUL-terminated string back, but
 * validate() only asks that PROVISIONING_SERIAL_LEN itself contain either a
 * full run of valid characters or valid characters followed by NUL padding. */
static void serial_full_length_no_nul_accepted(void)
{
	struct provisioning_record r;

	build(&r, PROVISIONING_ROLE_DONGLE);
	memcpy(r.set_serial, "RR-012345678", PROVISIONING_SERIAL_LEN); /* 12 chars, no NUL within them */
	r.set_serial[PROVISIONING_SERIAL_LEN] = '\0';

	enum provisioning_status st = provisioning_validate(&r);

	CHECK(st == PROVISIONING_OK, "got %s", provisioning_status_str(st));
}

static void serial_garbage_after_nul_rejected(void)
{
	struct provisioning_record r;

	build(&r, PROVISIONING_ROLE_DONGLE); /* "RR-0001\0\0\0\0\0" */
	r.set_serial[11] = 'X'; /* last serial byte, past the NUL build() left */

	enum provisioning_status st = provisioning_validate(&r);

	CHECK(st == PROVISIONING_ERR_SERIAL, "got %s", provisioning_status_str(st));
}

static void serial_all_nul_rejected(void)
{
	struct provisioning_record r;

	build(&r, PROVISIONING_ROLE_DONGLE);
	memset(r.set_serial, 0, PROVISIONING_SERIAL_LEN);

	enum provisioning_status st = provisioning_validate(&r);

	CHECK(st == PROVISIONING_ERR_SERIAL, "got %s", provisioning_status_str(st));
}

static void bad_role_rejected(void)
{
	struct provisioning_record r;

	build(&r, PROVISIONING_ROLE_DONGLE);
	r.role = (enum provisioning_role)3; /* one past the last defined role */

	enum provisioning_status st = provisioning_validate(&r);

	CHECK(st == PROVISIONING_ERR_ROLE, "got %s", provisioning_status_str(st));
}

/* The sentinel this exists for: a provisioning_data.h nobody actually ran
 * provision.py to generate (an empty template, a stray zeroed struct) must
 * not be indistinguishable from a real one — set_key all-zero is what
 * provision.py's secrets.token_bytes() practically never produces, so it's
 * the signal that this header was never really generated. */
static void all_zero_key_rejected(void)
{
	struct provisioning_record r;

	build(&r, PROVISIONING_ROLE_DONGLE);
	memset(r.set_key, 0, PROVISIONING_KEY_LEN);

	enum provisioning_status st = provisioning_validate(&r);

	CHECK(st == PROVISIONING_ERR_KEY, "got %s", provisioning_status_str(st));
}

/* One non-zero byte anywhere in the key is enough to not be the sentinel —
 * the check must scan the whole key, not just the first byte. */
static void key_single_nonzero_byte_accepted(void)
{
	struct provisioning_record r;

	build(&r, PROVISIONING_ROLE_DONGLE);
	memset(r.set_key, 0, PROVISIONING_KEY_LEN);
	r.set_key[PROVISIONING_KEY_LEN - 1] = 0x01u;

	enum provisioning_status st = provisioning_validate(&r);

	CHECK(st == PROVISIONING_OK, "got %s", provisioning_status_str(st));
}

/* ------------------------------------------------------------------------ */

int main(void)
{
	struct {
		const char *name;
		void (*fn)(void);
	} tests[] = {
		{ "valid record passes",              valid_record_passes },
		{ "all three roles accepted",         all_three_roles_accepted },
		{ "serial bad char rejected",         serial_bad_char_rejected },
		{ "serial full length, no NUL",       serial_full_length_no_nul_accepted },
		{ "serial garbage after NUL",         serial_garbage_after_nul_rejected },
		{ "serial all-NUL rejected",          serial_all_nul_rejected },
		{ "bad role rejected",                bad_role_rejected },
		{ "all-zero key rejected",            all_zero_key_rejected },
		{ "key single nonzero byte accepted", key_single_nonzero_byte_accepted },
	};

	for (size_t i = 0; i < sizeof(tests) / sizeof(tests[0]); i++) {
		int before = failures;

		tests[i].fn();
		printf("%s %s\n", failures == before ? "ok  " : "FAIL", tests[i].name);
	}

	printf("\n%d checks, %d failures\n", checks, failures);
	return failures == 0 ? 0 : 1;
}
